### ISSUE TITLE
Error after setup following the document

### ISSUE THREAD

**Issue by danielk44** [kanayak123/pyadselfservice#3]
I get "Forbidden You don't have permission to access / on this server" after completed the setup following the documents http://blogger.iamamazing.in/2016/10/web-based-python3-password-reset-tool.html
and just checking, many paths in the document seem to different.

eg.    WSGIScriptAlias / /opt/django-pyadselfservice/pyadselfservice/wsgi.py

I can only locate the wsgi.py file in 
/opt/django-pyadselfservice/pyadselfservice/pyadselfservice/pyadselfservice/wsgi.py

Alias /static/ /opt/django-pyadselfservice/static/ 
in Alias /static/ /opt/django-pyadselfservice/pyadselfservice/static/

Please advise.
Thanks in advance

**Comment by kanayak123** [comment]
@danielk44 Sorry for delay in reply. 
The paths for the documents must be as per the actual paths. In your case, the folder names are duplicated many times, I think due to unzipping. I suggest to clone the git repo.
If your wsgi.py file is in /opt/django-pyadselfservice/pyadselfservice/pyadselfservice/pyadselfservice/ then your apache config file would be something like below. If your Apache configuration and the folder permission is correct, there is no other thing that will cause 403 "Forbidden" error.

```
WSGIScriptAlias / /opt/django-pyadselfservice/pyadselfservice/pyadselfservice/pyadselfservice/wsgi.py
WSGIPythonPath /opt/django-pyadselfservice/pyadselfservice/pyadselfservice/

<VirtualHost *:80>
        Alias /static/ /opt/django-pyadselfservice/pyadselfservice/pyadselfservice/static/
        <Directory /opt/django-pyadselfservice/pyadselfservice/pyadselfservice/static>
            Require all granted
        </Directory>
        <Directory /opt/django-pyadselfservice/pyadselfservice/pyadselfservice/>
           <Files wsgi.py>
             Require all granted
           </Files>
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

**Comment by kanayak123** [comment]
Hey @danielk44 ,
I hope everything is working for you now.. I will close this ticket for now
